version: '3'
services:
  app:
    build: .
    ports:
      - '80:80'
    depends_on:
      - postgres
    env_file: .env

  postgres:
    image: postgres:14.2-alpine
    env_file: .env
    volumes:
      - ./:/var/lib/postgresql
